name: lmhsgeocaching
description: LMHS Geocaching App.
version: 1.0.0+1


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_phoenix: ^1.0.0
  url_launcher: ^6.0.6
  mailer: ^3.0.4
  flutter_email_sender: ^5.1.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.11
  provider: ^3.0.0
  location: ^2.3.5
  flutter_compass: '^0.7.0'
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  geodesy: 0.3.2
  geolocator: ^9.0.0
  cupertino_icons: ^0.1.3
  path_provider: ^2.0.2
  firebase_storage: ^8.1.1
  get: ^3.21.3
  text_item_selector: any
  flutter_signin_button: ^2.0.0
  permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - badge-images/badge_data.json
    - badge-images/collection_data.json
    - badge-images/barn.jpg
    - badge-images/church.jpg
    - badge-images/double.jpg
    - badge-images/googlelogo.jpg
    - badge-images/hotel.jpg
    - badge-images/mill.jpg
    - badge-images/school.jpg
    - badge-images/coin.jpg
    - badge-images/logo.png