name: lmhsgeocaching
description: LMHS Geocaching App.
version: 1.0.0+1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_phoenix: ^1.0.0
  url_launcher: ^6.0.6
  mailer: ^5.3.0
  flutter_email_sender: ^5.1.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.0
  provider: ^6.0.5
  location: ^4.0.0
  flutter_compass: ^0.7.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_messaging: ^14.1.4
  firebase_storage: ^11.0.8
  cloud_firestore: ^4.2.0
  google_sign_in: ^5.0.4
  qr_code_scanner: ^1.0.0
  geodesy: 0.4.0-nullsafety.0
  geolocator: ^9.0.0
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.2
  get: ^4.6.5
  flutter_signin_button: ^2.0.0
  permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - badge-images/badge_data.json
    - badge-images/collection_data.json
    - badge-images/alpha_tester.jpg
    - badge-images/barn.jpg
    - badge-images/church.jpg
    - badge-images/double.jpg
    - badge-images/googlelogo.jpg
    - badge-images/hotel.jpg
    - badge-images/mill.jpg
    - badge-images/school.jpg
    - badge-images/steam.jpg
    - badge-images/coin.jpg
    - badge-images/logo.png